version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app_laravel
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./docker/default.conf:/etc/nginx/sites-available/default
    ports:
      - "8080:80"
    command: php -S 0.0.0.0:80 -t /var/www
    networks:
      - app_laravel
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: app_postgres
    environment:
      POSTGRES_DB: app_school
      POSTGRES_USER: app_school
      POSTGRES_PASSWORD: app_school
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: app_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app_laravel

volumes:
  postgres_data:
  redis_data:

networks:
  app_laravel:
    driver: bridge
